#!/usr/bin/env bash

CONFIGURE_FILE=.configure
if [ -f ${CONFIGURE_FILE} ]; then
  source ${CONFIGURE_FILE}
fi

CMAKE_C_COMPILER=${CMAKE_C_COMPILER:-/usr/bin/gcc}
CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER:-/usr/bin/g++}
CMAKE_GENERATOR=${CMAKE_GENERATOR:-"Unix Makefiles"}
CMAKE_BUILD_WITH_INSTALL_RPATH=${CMAKE_BUILD_WITH_INSTALL_RPATH:-ON}
CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-Debug}
BUILD_DIR=${BUILD_DIR:-build}

cmake -B "${BUILD_DIR}" \
      -G "${CMAKE_GENERATOR}" \
      -S . \
      -DCMAKE_BUILD_WITH_INSTALL_RPATH="${CMAKE_BUILD_WITH_INSTALL_RPATH}" \
      -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=./cmake/conan_provider.cmake \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
      -DCMAKE_C_COMPILER="${CMAKE_C_COMPILER}" \
      -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}"
